#!/usr/bin/env node
/**
 * Development Startup Script
 * Auto-generated by init-dev-environment.js
 */

const { spawn } = require('child_process');
const { execSync } = require('child_process');

console.log('🚀 Starting FormFlowAI Development Environment...');

// Kill any existing processes on development ports
try {
    execSync('taskkill //f //im node.exe', { stdio: 'ignore' });
} catch (e) {
    // Ignore errors
}

// Start backend
console.log('🔧 Starting Backend Server...');
const backend = spawn('npm', ['run', 'dev:backend'], {
    cwd: process.cwd(),
    stdio: ['pipe', 'pipe', 'pipe'],
    shell: true
});

backend.stdout.on('data', (data) => {
    console.log('[Backend]', data.toString());
});

backend.stderr.on('data', (data) => {
    console.error('[Backend Error]', data.toString());
});

// Wait a bit for backend to start, then start frontend
setTimeout(() => {
    console.log('🎨 Starting Frontend Server...');
    const frontend = spawn('npm', ['run', 'dev'], {
        cwd: process.cwd(),
        stdio: ['pipe', 'pipe', 'pipe'],
        shell: true
    });

    frontend.stdout.on('data', (data) => {
        console.log('[Frontend]', data.toString());
    });

    frontend.stderr.on('data', (data) => {
        console.error('[Frontend Error]', data.toString());
    });
}, 5000);

console.log('✅ Development servers starting...');
console.log('📱 Frontend: http://localhost:5173');
console.log('🔧 Backend: http://localhost:3000');
console.log('💾 Backend Health: http://localhost:3000/health');
